package jtv.dao.entity.partner;

public enum PartnerStatus {
    ACTIVE,
    INACTIVE,
//    PLATFORM_ENROLLMENT_ACTIVE,
//    PLATFORM_ENROLLMENT_SUSPENDED,
//    PLATFORM_ENROLLMENT_TERMINATED,
    REGISTRATION_IN_PROGRESS,
    REGISTRATION_COMPLETED
}

